services:
  paper-search:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scholar-paper-search
    env_file:
      - .env
    ports:
      - "8001:8001"
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=8001
      - DEBUG=${DEBUG:-False}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - RABBITMQ_HOST=user-rabbitmq
      - RABBITMQ_PORT=5672
    volumes:
      - ./logs:/app/logs
    networks:
      - scholarai-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

# Connect to existing network from main orchestration
networks:
  scholarai-network:
    external: true
    name: docker_scholarai-network
